version: '3.1'

services:
    www:
        container_name: nginx
        image: nginx:alpine
        build:
           context: .
           dockerfile: Dockerfile
        ports:
          - "80:80"
        depends_on:
          - back
          - front

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./bdd/:/data/db
        ports:
        - 27017:27017

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        ports:
        - 8090:8081

    back:
        container_name: back
        build:
          args:
            user: daegon
            uid: 1000
          context: ./back
          dockerfile: Dockerfile
        restart: always
        ports:
        - 3000:3000
        depends_on: 
          - mongo

    front:
        container_name: front
        build:
            args:
                user: daegon
                uid: 1000
            context: ./front
            dockerfile: Dockerfile
        depends_on: 
            - back

    youtube:
        container_name: youtube
        build:
            context: ./services/youtube
            dockerfile: Dockerfile
        restart: always
        ports:
        - 3003:3003
        depends_on: 
            - front

    weather:
        container_name: weather
        build:
            context: ./services/weather
            dockerfile: Dockerfile
        restart: always
        ports:
        - 3001:3001
        depends_on: 
            - front

    todo:
        container_name: todo
        build:
            context: ./services/todo
            dockerfile: Dockerfile
        restart: always
        ports:
        - 3004:3004
        depends_on: 
            - front

    time:
        container_name: time
        build:
            context: ./services/time
            dockerfile: Dockerfile
        restart: always
        ports:
        - 3002:3002
        depends_on: 
            - front

    covid:
        container_name: covid
        build:
            context: ./services/covid-19
            dockerfile: Dockerfile
        restart: always
        ports:
        - 3005:3005
        depends_on: 
            - front