version: '3.1'

services:
    www:
        restart: always
        image: nginx:alpine
        volumes:
          - ./etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
          - "8080:8080"
        depends_on:
          - back
          - front

    mongo:
        restart: always
        image: mongo
        volumes:
          - /home/yobar/FunSport-bdd/:/data/db:rw
        ports:
        - 27017:27017

    mongo-express:
        restart: always
        image: mongo-express
        ports:
        - 8090:8081
        depends_on:
          - mongo

    back:
        restart: always
        build:
          context: ./back
        ports:
        - 3000:3000
        depends_on:
          - mongo

    front:
        restart: always
        build:
            context: ./front
