version: '3.1'

services:
    www:
        restart: always
        image: nginx:alpine
        volumes:
          - ./etc/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
          - ./front/dist:/usr/share/nginx/www:ro

        ports:
          - 81:80

